spring:
 application:
  name: movie_service
 profiles.active: local

server:
  port: 8082

---
# Local environment configuration
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      database: learnsquad
      port: 27017
      host: localhost
